Resolvendo os conflitos!
SalvatoreAcademyEmpresa/gerenciamento-de-tarefas pull request #22
Opened 2024-07-09 23:03 UTC by F-K-C

2024-07-09 23:04 UTC, paulosalvatore requested changes
Adicionar o arquivo `.gitignore`, excluindo a `node_modules`

2024-07-09 23:05 UTC, paulosalvatore commented on backend/index.js
> +    const db = Client.db(dbName)
```suggestion
    const client = new MongoClient(dbUrl)
    console.log("Conectando ao banco de dados")
    await client.connect()
    console.log("Banco de dados conectado com sucesso!")

    const db = client.db(dbName)
```

2024-07-09 23:06 UTC, paulosalvatore commented on backend/index.js
> +main()
```suggestion
main()

```

2024-07-09 23:07 UTC, paulosalvatore commented on backend/index.js
> +const dbUrl = 'mongodb+srv://admin:AlanFabsEstudoSalvatore24@cluster0.hmmuzy9.mongodb.net'
Sugiro já instalar o dotenv e colocar essa info sensível numa variável de ambiente.

2024-07-09 23:09 UTC, paulosalvatore commented on backend/package.json
> +<<<<<<< HEAD
Conflito não foi bem resolvido, precisa garantir que o projeto está rodando. Com essas linhas aqui, vai quebrar.

2024-07-26 19:16 UTC, alanrochagomes submitted a review, later dismissed

2024-07-26 20:15 UTC, alanrochagomes commented on backend/db/database-connection.js
É opcional, mas seria bom incluir um monitoramento com `SIGINT` para fechar a conexão corretamente.

2024-07-29 20:45 UTC, alanrochagomes requested changes

2024-07-29 20:45 UTC, alanrochagomes commented on backend/tarefas/tarefas.controller.js
No front está  `text` e não `nome`

2024-07-30 22:42 UTC, paulosalvatore commented
@F-K-C Mudei o assigne dessa issue para o @alanrochagomes, para conseguirmos finalizar a revisão e avançar no desenvolvimento do backend.

2024-08-06 23:12 UTC, paulosalvatore approved these changes

2024-08-06 23:13 UTC, merged