31 fase 1 backend implementar middleware de validação com joi
SalvatoreAcademyEmpresa/gerenciamento-de-tarefas pull request #50
Opened 2024-08-19 17:49 UTC by F-K-C

JOI implementado!

2024-08-19 20:45 UTC, paulosalvatore requested changes
Revisão de código, formatação e sugestões de melhorias.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.router.js
> +module.exports = router;
Sempre bom ter uma linha em branco no fim do arquivo.
```suggestion
module.exports = router;

```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  /*const newItem = req.body;
Trechos comentados sem muito propósito.
Sugiro removê-los.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  res.status(201).send(newItem);*/
Trechos comentados sem muito propósito.
Sugiro removê-los.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  if(error){
Acredito que valha adicionar um formatador automático como o Prettier.
```suggestion
  if (error){
```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  res.send(updatedItem)
```suggestion
  if (!updatedItem){
    return res.status(404).send("Item não encontrado para atualização");
  }

  res.send(updatedItem)
```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  res.send(newItem);*/
Trechos comentados sem muito propósito.
Sugiro removê-los.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  //await service.deleteById(id);
Trechos comentados sem muito propósito.
Sugiro removê-los.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.controller.js
> +  if(!result){
Espaçamento para melhorar legibilidade.
```suggestion
  if (!result) {
```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.validation.js
> +const Joi = require("joi");
Atualizar o espaçamento do arquivo para 2 espaços, mantendo o padrão do resto do projeto.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.validation.js
> +const updateTaskSchema = Joi.object({
Acredito que esteja repetindo muitas regras de validação.
**Problemas:**
- Se precisar editar um lugar, vai precisar editar em vários.
- Se precisar criar um novo endpoint seguindo essa mesma lógica, vai precisar de um novo objeto, deixando mais difícil a manutenção e mais propenso a error.

Minha sugestão é seguir como está na missão de aprendizado, criando uma única entidade e usando a mesma validação para ambos os casos.

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.validation.js
> +    next();
Melhorar os espaçamentos. Colocar o prettier vai resolver.
```suggestion

    if (error) {
        return res.status(400).json({ error: error.details.map(err => err.message).join(", ") });
    }

    next();
```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.validation.js
> +    next();
```suggestion
    const { error } = updateTaskSchema.validate(req.body);

    if (error) {
        return res.status(400).json({ error: error.details.map(err => err.message).join(", ") });
    }

    next();
```

2024-08-19 20:45 UTC, paulosalvatore commented on backend/tasks/tasks.validation.js
> +};
```suggestion
};

```

2024-08-20 14:52 UTC, alanrochagomes requested changes

2024-08-20 14:52 UTC, alanrochagomes commented on backend/tasks/tasks.validation.js
Uma sugestão, caso queira optar por isso, na mensagem de erro de atualização, se quer permitir que o título ou a descrição não sejam obrigatórios, pode ajustar o **updateTaskSchema** para não exigir **required()**."

2024-10-17 19:04 UTC, closed without merging