56 fase 2 backend definir modelos de dados schemas de comentários
SalvatoreAcademyEmpresa/gerenciamento-de-tarefas pull request #58
Opened 2024-09-05 18:58 UTC by F-K-C

Utilização do JOI

2024-09-06 16:22 UTC, alanrochagomes commented on backend/Comentários/comment.controller.js
Sugestões de melhorias e boas práticas: No método updateComment, nomeou a variável como updateComment, mas seria melhor algo como updatedComment para indicar que a operação foi concluída.

2024-09-06 16:51 UTC, alanrochagomes requested changes

2024-09-06 16:51 UTC, alanrochagomes commented on backend/Comentários/comment.controller.js
**Erro de digitação** em `updateComment`:

No bloco catch de `updateComment`, há um pequeno erro de digitação: _commment_. Corrija para **_comment_**

2024-09-06 16:51 UTC, alanrochagomes commented on backend/Comentários/comment.controller.js
**Uso do código de status:**

No método `deleteComment`, se o comentário não for encontrado, você poderia retornar o código de status 204 No Content em vez de 200 para indicar que a operação foi bem-sucedida, mas não há conteúdo para retornar. Isso poderia ser mais semântico.

2024-09-11 10:48 UTC, F-K-C commented on backend/Comentários/comment.controller.js
Atualizado!

2024-09-11 10:54 UTC, F-K-C commented on backend/Comentários/comment.controller.js
Olá Alan, acho que não entendi bem essa passagem. Você diz com relação a linha de código abaixo? Nessa linha, que estamos usando o comando 200, o comentário está sendo deletado com sucesso.

            res.status(200).json({ message: 'Comment deleted successfully'});            

A linha em que o comentário não está sendo encontrado é a debaixo, com o comando 404, você se refere a essa, sugerindo que fosse 204?

            res.status(404).json({ message: 'Comment not found'});

2024-09-11 12:06 UTC, alanrochagomes commented on backend/Comentários/comment.controller.js
Quando o comentário é deletado, não há necessidade de retornar conteúdo, o código 204 (No Content) seria mais adequado. Exemplo:

```
if (result) {
    res.status(204).send(); // Código 204 não retorna conteúdo
} else {
    res.status(404).json({ message: 'Comment not found' });
}
```
O código 204 indica que a operação foi bem-sucedida, mas não há resposta de corpo, o que faz mais sentido do que o 200, que tradicionalmente espera uma resposta de conteúdo. Mas se quiser manter assim também é válido, não vai estar errado.

2024-09-13 16:52 UTC, F-K-C commented on backend/Comentários/comment.controller.js
Resolvido!

2024-09-13 16:53 UTC, F-K-C commented on backend/Comentários/comment.controller.js
Ok, entendi! Alterado!

2024-09-13 16:57 UTC, alanrochagomes approved these changes

2024-09-13 17:00 UTC, merged